web:
  build: .
  ports:
   - "8080:8080"
  environment:
   SPRING_DATA_MONGODB_URI: mongodb://mongo/loksfee
  #volumes:
  # - ./target:./data
  links:
   - mongo
mongo:
  image: mongo
  ports:
   - "27017:27017"
